package com.desafio.apirest.resources;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.CrossOrigin;
import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.PutMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;

import org.springframework.web.bind.annotation.RestController;

import com.desafio.apirest.models.Turma;
import com.desafio.apirest.repository.TurmaRepository;
import com.desafio.apirest.response.ResponseHandler;

import io.swagger.annotations.Api;
import io.swagger.annotations.ApiOperation;

import java.util.List;

@RestController
@RequestMapping(value = "/api")
@Api(value = "API REST Desafio")
@CrossOrigin(origins = "*")
public class TurmaResource {

	@Autowired
	TurmaRepository turmaRepository;

	// endpoint para buscar todas as turmas cadastradas no banco de dados, utilizar @GET na requisição
	@GetMapping("/turmas")
	@ApiOperation(value = "Retorna uma lista de turmas")
	public ResponseEntity<Object> getAll() {
		if (turmaRepository.count() != 0) {
			List<Turma> result = turmaRepository.findAll();
			return ResponseHandler.generateResponse("Dados encontrados com sucesso", HttpStatus.OK, result);
		} else {
			return ResponseHandler.generateResponse("Não existem turmas cadastrados", HttpStatus.OK, null);
		}

	}

	// endpoint para buscar turmas por id, utilizar @GET na requisição
	@GetMapping("/turma/{id}")
	@ApiOperation(value = "Retorna uma turma filtrada por id")
	public ResponseEntity<Object> getById(@PathVariable(value = "id") long id) {
		if (turmaRepository.existsById(id)) {
			Turma result = turmaRepository.findById(id);
			return ResponseHandler.generateResponse("Turma encontrada com sucesso!", HttpStatus.OK, result);
		} else {
			return ResponseHandler.generateResponse("Não existe turma cadastrada com esse ID", HttpStatus.OK, null);
		}

	}

	// endpoint para criar turma, utilizar @POST na requisição e não passar ID no json por já ser autogenerated
	@PostMapping("/turma/create")
	@ApiOperation(value = "Cria uma nova turma via json")
	public ResponseEntity<Object> create(@RequestBody Turma turma) {
		Turma result = turmaRepository.save(turma);
		if (result.getNome() != null && (Integer) result.getCapacidade() != null) {
			return ResponseHandler.generateResponse("Turma cadastrada com sucesso!", HttpStatus.OK, result);
		} else {
			return ResponseHandler.generateResponse("Todos os campos precisam ser enviados pelo json", HttpStatus.OK,
					result);
		}

	}

	// endpoint para deletar turmas, utilizar @DELETE na requisição
	@DeleteMapping("/turma/delete/{id}")
	@ApiOperation(value = "Deleta uma turma via id")
	public ResponseEntity<Object> deleteById(@PathVariable("id") long id) {
		if (turmaRepository.existsById(id)) {
			Turma result = turmaRepository.deleteById(id);
			return ResponseHandler.generateResponse("Turma excluída com sucesso!", HttpStatus.OK, result);
		} else {
			return ResponseHandler.generateResponse("Não existe turma cadastrada com esse ID", HttpStatus.OK, null);
		}
	}

	// endpoint para atualizar turma, utilizar @PUT na requisição
	@PutMapping("/turma/update")
	@ApiOperation(value = "Atualiza uma turma via json")
	public ResponseEntity<Object> update(@RequestBody Turma turma) {
		Turma result = turmaRepository.save(turma);
		return ResponseHandler.generateResponse("Turma atualizada com sucesso!", HttpStatus.OK, result);
	}

}
